language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
before_script:
  - mkdir build
  - cmake -H./tools -B./build
script:
  - make -C ./build

